//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindaSVS.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public class Customer
    {
        public Customer()
        {
            this.QuoteRequestMessages = new HashSet<QuoteRequestMessage>();
            this.QuoteRequests = new HashSet<QuoteRequest>();
            this.Orders = new HashSet<Order>();
            this.Messages = new HashSet<Message>();
        }
    
        public int CustomerId { get; set; }
        public int UserId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string HomePhoneNumber { get; set; }
        public string CellPhoneNumber { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string Province { get; set; }
        public string Country { get; set; }
        public string PostalCode { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<QuoteRequestMessage> QuoteRequestMessages { get; set; }
        public virtual ICollection<QuoteRequest> QuoteRequests { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
        public virtual ICollection<Message> Messages { get; set; }
    }
}
