//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindaSVS.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public class Message
    {
        public Message()
        {
            this.ReplyMessages = new HashSet<Message>();
        }

        public int MessageId { get; set; }
        public Nullable<int> ParentId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> ProviderId { get; set; }
        public string MessageContent { get; set; }
        public Nullable<System.DateTime> MessageDateTime { get; set; }

        public virtual Customer Customer { get; set; }
        public virtual ICollection<Message> ReplyMessages { get; set; }
        public virtual Message ParentMessage { get; set; }
        public virtual Provider Provider { get; set; }
    }
}
