//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindaSVS.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public class QuoteRequest
    {
        public QuoteRequest()
        {
            this.QuoteRequestMessages = new HashSet<QuoteRequestMessage>();
            this.QuoteRequestUploads = new HashSet<QuoteRequestUpload>();
            this.Quotes = new HashSet<Quote>();
        }
    
        public int QuoteQuestId { get; set; }
        public int CustomerId { get; set; }
        public int ServiceId { get; set; }
        public System.DateTime QuoteDateTime { get; set; }
        public byte Status { get; set; }
        public string Description { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual ICollection<QuoteRequestMessage> QuoteRequestMessages { get; set; }
        public virtual Service Service { get; set; }
        public virtual ICollection<QuoteRequestUpload> QuoteRequestUploads { get; set; }
        public virtual ICollection<Quote> Quotes { get; set; }
    }
}
