//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindaSVS.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public class ServiceCatalog
    {
        public ServiceCatalog()
        {
            this.ChildServiceCatalogs = new HashSet<ServiceCatalog>();
            this.Services = new HashSet<Service>();
        }
    
        public int ServiceCatalogId { get; set; }
        public int? ParentId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<ServiceCatalog> ChildServiceCatalogs { get; set; }
        public virtual ServiceCatalog ParentServiceCatalog { get; set; }
        public virtual ICollection<Service> Services { get; set; }
    }
}
