//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindaSVS.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public class User
    {
        public User()
        {
            this.Customers = new HashSet<Customer>();
            this.Providers = new HashSet<Provider>();
        }
    
        public int UserId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Address { get; set; }
        public string PostalCode { get; set; }
        public string City { get; set; }
        public string Province { get; set; }
        public string Country { get; set; }
        public Nullable<System.DateTime> RegisterDateTime { get; set; }
    
        public virtual ICollection<Customer> Customers { get; set; }
        public virtual ICollection<Provider> Providers { get; set; }
    }
}
