//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindaSVS.Data.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        public int JobId { get; set; }
        public int OrderId { get; set; }
        public int ScheduleId { get; set; }
        public bool IsReviewed { get; set; }
        public bool IsFixedRate { get; set; }
        public bool IsHourlyRate { get; set; }
        public decimal ActualRate { get; set; }
        public decimal ActualHours { get; set; }
        public Nullable<decimal> PartsRate { get; set; }
        public string Description { get; set; }
        public System.DateTime CompletedDateTime { get; set; }
        public byte Status { get; set; }
    
        public virtual Schedule Schedule { get; set; }
        public virtual Order Order { get; set; }
    }
}
