//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindaSVS.Data.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.Jobs = new HashSet<Job>();
        }
    
        public int OrderId { get; set; }
        public int QuoteResponseId { get; set; }
        public int CustomerId { get; set; }
        public int ProviderId { get; set; }
        public bool IsFixedRate { get; set; }
        public bool IsHourlyRate { get; set; }
        public decimal EstimatedRate { get; set; }
        public decimal EstimatedHours { get; set; }
        public string Description { get; set; }
        public System.DateTime OrderDateTime { get; set; }
        public System.DateTime ScheduleDateTime { get; set; }
        public byte Status { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual ICollection<Job> Jobs { get; set; }
        public virtual Provider Provider { get; set; }
        public virtual QuoteRespons QuoteRespons { get; set; }
    }
}
