//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindaSVS.Data.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Provider
    {
        public Provider()
        {
            this.Orders = new HashSet<Order>();
            this.QuoteMessages = new HashSet<QuoteMessage>();
            this.QuoteResponses = new HashSet<QuoteRespons>();
        }
    
        public int ProviderId { get; set; }
        public int UserId { get; set; }
        public string CompanyName { get; set; }
        public string OfficePhoneNumber { get; set; }
        public string CellPhoneNumber { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string Province { get; set; }
        public string Country { get; set; }
        public string PostalCode { get; set; }
    
        public virtual ICollection<Order> Orders { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<QuoteMessage> QuoteMessages { get; set; }
        public virtual ICollection<QuoteRespons> QuoteResponses { get; set; }
    }
}
