//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindaSVS.Data.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuoteRequestMessage
    {
        public int QuoteRequestMessageId { get; set; }
        public int QuoteQuestId { get; set; }
        public int CustomerId { get; set; }
        public int ProviderId { get; set; }
        public bool IsInbound { get; set; }
        public string MessageContent { get; set; }
        public System.DateTime MessageDateTime { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Provider Provider { get; set; }
        public virtual QuoteRequest QuoteRequest { get; set; }
    }
}
