//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindaSVS.Data.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuoteRequestUpload
    {
        public int QuoteRequestUploadId { get; set; }
        public int QuoteRequestId { get; set; }
        public string FilePath { get; set; }
        public string Decription { get; set; }
        public System.DateTime UploadDateTime { get; set; }
    
        public virtual QuoteRequest QuoteRequest { get; set; }
    }
}
