//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindaSVS.Data.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quote
    {
        public Quote()
        {
            this.QuoteResponses = new HashSet<QuoteRespons>();
            this.QuoteUploads = new HashSet<QuoteUpload>();
        }
    
        public int QuoteId { get; set; }
        public int CustomerId { get; set; }
        public int ServiceId { get; set; }
        public System.DateTime QuoteDateTime { get; set; }
        public byte Status { get; set; }
        public string Description { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual ICollection<QuoteRespons> QuoteResponses { get; set; }
        public virtual Service Service { get; set; }
        public virtual ICollection<QuoteUpload> QuoteUploads { get; set; }
    }
}
