//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindaSVS.Data.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuoteMessage
    {
        public int QuoteMessageId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> ProviderId { get; set; }
        public Nullable<bool> IsInbound { get; set; }
        public string MessageContent { get; set; }
        public Nullable<System.DateTime> MessageDateTime { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Provider Provider { get; set; }
    }
}
