//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindaSVS.Data.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public Schedule()
        {
            this.Jobs = new HashSet<Job>();
        }
    
        public int ScheduleId { get; set; }
        public int ProviderId { get; set; }
        public int JobId { get; set; }
        public string Title { get; set; }
        public string Location { get; set; }
        public System.DateTime StartDateTime { get; set; }
        public System.DateTime EndDateTime { get; set; }
        public byte Status { get; set; }
    
        public virtual ICollection<Job> Jobs { get; set; }
    }
}
