//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindaSVS.Data.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceCatalog
    {
        public ServiceCatalog()
        {
            this.ServiceCatalogs1 = new HashSet<ServiceCatalog>();
            this.Services = new HashSet<Service>();
        }
    
        public int ServiceCatalogId { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<ServiceCatalog> ServiceCatalogs1 { get; set; }
        public virtual ServiceCatalog ServiceCatalog1 { get; set; }
        public virtual ICollection<Service> Services { get; set; }
    }
}
